kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: siacdn-backend
  namespace: sia
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
