kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sia-volume-claim
  namespace: sia
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
