kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sia-prime-volume-claim
  namespace: sia
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
